# Generated by Django 2.2.1 on 2019-05-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='email address')),
                ('homepage', models.URLField(blank=True, verbose_name='home page')),
                ('comment', models.TextField(verbose_name='comment')),
                ('pub_date', models.DateTimeField(editable=False, verbose_name='Published date')),
                ('is_spam', models.BooleanField(default=False, editable=False, verbose_name='spam?')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
