"""
Django settings for Djangoexample project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from datetime import timedelta

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ecfc!s7=q^x*nu++$j6xwy@8x+0in$r90jzrshm_c0nln5$^bl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_results',
    'django_celery_beat',
    'hello.apps.HelloConfig',
    # 'django-crontab'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Djangoexample.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Djangoexample.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# Celery定时任务设置
CELERY_RESULT_BACKEND = 'django-db'
from celery.schedules import crontab

# CELERY_BROKER_URL = 'redis://localhost:6379'
# Let's make things happen


# CELERYBEAT_SCHEDULE = {
#     'task1': {
#         'task': 'hello.tasks.send_notification',
#         'schedule': timedelta(seconds=10),
#         'args': ()
#     }
# }
# CELERYBEAT_SCHEDULE = {
#     'send-summary-every-hour': {
#         'task': 'summary',
#         # There are 4 ways we can handle time, read further
#         'schedule': 3600.0,
#         # If you're using any arguments
#         'args': ('We don’t need any',),
#     },
#     # Executes every Friday at 4pm
#     'send-notification-on-friday-afternoon': {
#         'task': 'hello.tasks.send_notification',
#         'schedule': crontab(hour=19, minute=2),
#     },
#     'task1': {
#         'task': 'hello.tasks.send_notification',
#         'schedule': crontab(hour=7, minute=2),
#     },
# }
#
# # django-contrb定时任务
# CRONJOBS = (
#     # ('*/1 * * * *', '你的app名.定时函数所在的py文件名.定时函数名'),
#     ('*/1 * * * *', 'hello.tasks.send_notifiction'),
#     # ('0   0 1 * *', '你的app名.定时函数所在的py文件名.定时函数名', '> 输出文件路径和名称'),
# )
#
# CELERY_TIMEZONE = 'UTC'
#

# 防止死锁
CELERYD_FORCE_EXECV = True
